export const ADMIN_ROUTE = '/admin'
export const CART_ROUTE = '/cart'

export const AUTHORIZATION_ROUTE = '/authorization'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/shop'
export const TOY_ROUTE = '/toy'
export const HOME_ROUTE = '/'
export const NEWS_ROUTE = '/news'
export const USER_ROUTE = '/user'
